site_name: Mint-Docu
copyright: Copyright &copy; 2025 Pitz
nav:
  - Home:
    - index.md
  - Mathe:
    - mathe/index.md
    - 11b:
      - mathe/11b/index.md
      - 01 Ganzrationale Funktionen:
        - 01 Ganzrationale Funktionen: mathe/11b/01_ganzrationale_funktionen/info_01_ganzrat-funktionen.md
        - 02 Ableitungen ganzr. Funktionen: mathe/11b/01_ganzrationale_funktionen/info_02_grf_ableitungen.md
        - 03 Nullstellen ganzr. Funktionen: mathe/11b/01_ganzrationale_funktionen/info_03_grf_nullstellen.md

      - 02 Exponentialfunktionen:
        - 01 Quotiententest: mathe/11b/02_exponential_funktionen/info_01_Quotiententest.md
        - 02 Logarithmus: mathe/11b/02_exponential_funktionen/info_02_Logarithmus.md
        - 03 Anwendungsaufgaben: mathe/11b/02_exponential_funktionen/info_03_Anwendungsaufgaben.md
        - 04 Umrechnen der Basis: mathe/11b/02_exponential_funktionen/info_04_Umrechnen_der_Basis.md
        - 05 Ableitungen: mathe/11b/02_exponential_funktionen/info_05_Ableitungen.md

      - 03 Trigonometrische Funktionen:
        - 01 Einzeitskreis: mathe/11b/03_trigonometrische_funktionen/info_01_einheitskreis.md
        - 02 Trigon. Funktionen Verschieben, Strecken: mathe/11b/03_trigonometrische_funktionen/info_02_geom_funkt_versch.md
        - 03 Lösungen von gem. Funktionen: mathe/11b/03_trigonometrische_funktionen/info_03_trigonom-gleichungen.md
        - 04 Geom. Funktionen ableiten: mathe/11b/03_trigonometrische_funktionen/info_04_sin-cos-ableitungen.md
        - 05 Hoch- und Tiefpunkte: mathe/11b/03_trigonometrische_funktionen/info_05_hoch_tiefpunkte.md
        - 06 Riesenrad: mathe/11b/03_trigonometrische_funktionen/info_06_riesenrad.md

      - Arbeitsblätter:
        - mathe/11b/work/index.md
        - 2025-04-05 mod-sin: mathe/11b/work/ws-2025-04-05.md
        - 2025-04-19 Ableitungen: mathe/11b/work/ws-2025-04-19.md
        - 2025-04-26 Nullstellen: mathe/11b/work/ws-2025-04-26.md
        - 2025-05-04 Geom. Funktionen: mathe/11b/work/ws-2025-05-04.md
        - 2025-05-04 Lösen v. Geom. Funktionen: mathe/11b/work/ws-2025-05-17.md

    - Q1:
      - mathe/Q1/index.md
      - Basics:
        - mathe/Q1/basics/index.md
        - Summenformel: mathe/Q1/basics/summenformel.md
        - Summenformel f. Quadratzahlen: mathe/Q1/basics/summenformel_quadrat.md
        - Lineare Gleichungssysteme: mathe/Q1/basics/gleichungssysteme.md
        - Formen Quadratischer Gleichungen: mathe/Q1/basics/quadratische_gleichungen.md

      - Infos:
          - mathe/Q1/infos/index.md
          - Streifenmethode: mathe/Q1/infos/streifenmethode.md
          - Streifenmethode Teil 2: mathe/Q1/infos/streifenmethode2.md
          - Flächeninhaltsfunktion der Normalparabel: mathe/Q1/infos/flaecheninhaltsfunktion.md
          - Flächeninhaltsfunktion Beispiel Bahnhof: mathe/Q1/infos/flaecheninhaltsfunktion_uebung1.md
          - Flächeninhaltsfunktion Übung 13: mathe/Q1/infos/flaecheninhaltsfunktion_uebung2.md
          - Stammfunktion und unbestimmtes Integral: mathe/Q1/infos/stammfunktion.md
      - Arbeitsblätter:
          - Buch S. 17 Aufgabe 4: mathe/Q1/work/ws-buch-s17-a4.md
          - Buch S. 17 Aufgabe 5: mathe/Q1/work/ws-buch-s17-a5.md
          - Buch S. 31 Aufgabe 3: mathe/Q1/work/ws-buch-s31-a3.md
          - Buch S. 46: mathe/Q1/work/ws-buch-s46.md
          - Buch S. 49 Übung 1: mathe/Q1/work/ws-buch-s49-a1.md
          - Buch S. 51 Übung 1: mathe/Q1/work/ws-buch-s51-a1.md
          - Buch S. 52 Übung 2: mathe/Q1/work/ws-buch-s52-a2.md
          - Buch S. 55 Übung 7: mathe/Q1/work/ws-buch-s55-a7.md
          - Buch S. 55 Übung 8: mathe/Q1/work/ws-buch-s55-a8.md
          - Buch S. 56 Übung 9: mathe/Q1/work/ws-buch-s56-a9.md
          - KI gen. Aufgaben 1: mathe/Q1/work/ws-ki-test.md
          - KI gen. Aufgaben 2: mathe/Q1/work/ws-ki-test2.md


  - Informatik:
    - info/index.md
    - Minecraft:
      - info/minecraft/index.md
      - Setup: info/minecraft/setup.md
      - Beispiel Teil 1: info/minecraft/example_project_1.md
      - Beispiel Teil 2: info/minecraft/example_project_2.md
      - Mods in Fabric installieren: info/minecraft/mods_in_fabric.md
    - 11b:
      - info/11b/index.md
      - Infos:
        - info/11b/infos/index.md
      - Arbeitsblätter:
        - info/11b/work/index.md
    - Q1:
      - info/Q1/index.md
      - kara:
        - info/Q1/kara/index.md
        - Einführung in javakara: info/Q1/kara/einfuehrung.md
      - Java:
        - info/Q1/java/index.md
        - Linksammlung: info/Q1/java/linksammlung.md
        - Hallo World: info/Q1/java/hallo_world.md
      - Objektorientierte Programmierung:
        - info/Q1/oop/index.md
        - Was ist OOP?: info/Q1/oop/was_ist_oop.md
        - Was ist OOP - Beispiel: info/Q1/oop/was_ist_oop_beispiel.md
        - AB 1 - Aufg. 2 Baum: info/Q1/oop/ab1_2_aufg2.md
        - AB 1 - Aufg. 5 Bücher: info/Q1/oop/ab1_2_aufg5.md
        - AB 2 - Aufg. 1 Arzneiverwaltung: info/Q1/oop/ab2_aufg1.md


theme:
  name: material
  logo: img/pitz-logo.png
  favicon: assets/favicon.ico
  palette:
    primary: white
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.tooltips


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - tables
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.blocks.details
  - pymdownx.blocks.definition
  - pymdownx.blocks.admonition
  - pymdownx.blocks.html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
 - plantuml-colocator

extra:
  generator: false

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
